class Distancia:
    distancias_dict = {                 
        'Estádio_Al_Thumama':                                                   {'Estádio_Al_Thumama': (0, 0), 'Estádio_Al_Janoub': (9,12), 'Estádio_Al_Bayt': (46,58), 'Estádio_Ahmad_bin_Ali': (22,26), 'Estádio_Cidade_da_Educação': (14,19), 'Estádio_974': (7,13), 'Estádio_Internacional_Khalifa': (9,13), 'Estádio_Lusail': (21,32), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (106,115), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (16,25), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (5,9), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (9,12)}, 
        'Estádio_Al_Janoub':                                                    {'Estádio_Al_Thumama': (9, 13), 'Estádio_Al_Janoub': (0,0), 'Estádio_Al_Bayt': (55,68), 'Estádio_Ahmad_bin_Ali': (30,37), 'Estádio_Cidade_da_Educação': (22,30), 'Estádio_974': (14,17), 'Estádio_Internacional_Khalifa': (17,24), 'Estádio_Lusail': (30,41), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (115,126), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (25,36), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (14,20), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (18,23)},  
        'Estádio_Al_Bayt':                                                      {'Estádio_Al_Thumama': (46, 60), 'Estádio_Al_Janoub': (55,67), 'Estádio_Al_Bayt': (0,0), 'Estádio_Ahmad_bin_Ali': (38,46), 'Estádio_Cidade_da_Educação': (38,46), 'Estádio_974': (40,52), 'Estádio_Internacional_Khalifa': (43,53), 'Estádio_Lusail': (25,31), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (61,75), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (30,36), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (42,49), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (39,47)},
        'Estádio_Ahmad_bin_Ali':                                                {'Estádio_Al_Thumama': (21, 28), 'Estádio_Al_Janoub': (30,35), 'Estádio_Al_Bayt': (38,46), 'Estádio_Ahmad_bin_Ali': (0,0), 'Estádio_Cidade_da_Educação': (8,10), 'Estádio_974': (22,26), 'Estádio_Internacional_Khalifa': (12,15), 'Estádio_Lusail': (18,25), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (92,103), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (16,20), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (18,21), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (14,16)},
        'Estádio_Cidade_da_Educação':                                           {'Estádio_Al_Thumama': (13, 21), 'Estádio_Al_Janoub': (22,28), 'Estádio_Al_Bayt': (38,47), 'Estádio_Ahmad_bin_Ali': (8,10), 'Estádio_Cidade_da_Educação': (0,0), 'Estádio_974': (14,18), 'Estádio_Internacional_Khalifa': (5,10), 'Estádio_Lusail': (14,21), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (95,104), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (10,14), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (10,14), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (5,9)},
        'Estádio_974':                                                          {'Estádio_Al_Thumama': (6, 15), 'Estádio_Al_Janoub': (14,22), 'Estádio_Al_Bayt': (40,53), 'Estádio_Ahmad_bin_Ali': (22,31), 'Estádio_Cidade_da_Educação': (14,20), 'Estádio_974': (0,0), 'Estádio_Internacional_Khalifa': (12,17), 'Estádio_Lusail': (16,25), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (101,114), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (12,19), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (6,6), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (9,12)},
        'Estádio_Internacional_Khalifa':                                        {'Estádio_Al_Thumama': (9, 14), 'Estádio_Al_Janoub': (17,21), 'Estádio_Al_Bayt': (43,53), 'Estádio_Ahmad_bin_Ali': (12,20), 'Estádio_Cidade_da_Educação': (5,9), 'Estádio_974': (12,17), 'Estádio_Internacional_Khalifa': (0,0), 'Estádio_Lusail': (18,27), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (101,110), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (13,19), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (6,10), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (5,8)},   
        'Estádio_Lusail':                                                       {'Estádio_Al_Thumama': (21, 34), 'Estádio_Al_Janoub': (30,40), 'Estádio_Al_Bayt': (25,31), 'Estádio_Ahmad_bin_Ali': (18,25), 'Estádio_Cidade_da_Educação': (14,20), 'Estádio_974': (16,25), 'Estádio_Internacional_Khalifa': (18,26), 'Estádio_Lusail': (0,0), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (85,97), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (5,11), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (16,21), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (13,22)},   
        'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort':                          {'Estádio_Al_Thumama': (106, 118), 'Estádio_Al_Janoub': (115,125), 'Estádio_Al_Bayt': (61,76), 'Estádio_Ahmad_bin_Ali': (92,104), 'Estádio_Cidade_da_Educação': (95,104), 'Estádio_974': (101,116), 'Estádio_Internacional_Khalifa': (101,111), 'Estádio_Lusail': (85,98), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (0,0), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (90,103), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (101,115), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (97,106)},
        'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex':   {'Estádio_Al_Thumama': (16, 27), 'Estádio_Al_Janoub': (25,32), 'Estádio_Al_Bayt': (30,3600), 'Estádio_Ahmad_bin_Ali': (16,22), 'Estádio_Cidade_da_Educação': (10,14), 'Estádio_974': (12,19), 'Estádio_Internacional_Khalifa': (130,190), 'Estádio_Lusail': (5,10), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (90,102), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (0,0), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (11,15), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (8,12)},
        'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha':                         {'Estádio_Al_Thumama': (5, 11), 'Estádio_Al_Janoub': (14,18), 'Estádio_Al_Bayt': (42,50), 'Estádio_Ahmad_bin_Ali': (18,21), 'Estádio_Cidade_da_Educação': (9,15), 'Estádio_974': (6,8), 'Estádio_Internacional_Khalifa': (6,8), 'Estádio_Lusail': (16,22), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (101,110), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (11,16), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (0,0), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (4,7)},
        'Delegação_Francesa_(FFF)_Al_Messila_Resort':                           {'Estádio_Al_Thumama': (9, 16), 'Estádio_Al_Janoub': (18,23), 'Estádio_Al_Bayt': (39,47), 'Estádio_Ahmad_bin_Ali': (13,17), 'Estádio_Cidade_da_Educação': (5,8), 'Estádio_974': (9,13), 'Estádio_Internacional_Khalifa': (5,9), 'Estádio_Lusail': (13,21), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (97,104), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (8,13), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (4,8), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (0,0)},
    }

    distancias_inadmissivel = {
        'Estádio_Al_Thumama':                                                   {'Estádio_Al_Thumama': (0, 0), 'Estádio_Al_Janoub': (90,120), 'Estádio_Al_Bayt': (460,580), 'Estádio_Ahmad_bin_Ali': (220,260), 'Estádio_Cidade_da_Educação': (140,190), 'Estádio_974': (70,130), 'Estádio_Internacional_Khalifa': (90,130), 'Estádio_Lusail': (210,320), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (1060,1150), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (160,250), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (50,90), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (90,120)}, 
        'Estádio_Al_Janoub':                                                    {'Estádio_Al_Thumama': (90, 130), 'Estádio_Al_Janoub': (0,0), 'Estádio_Al_Bayt': (550,680), 'Estádio_Ahmad_bin_Ali': (300,370), 'Estádio_Cidade_da_Educação': (220,300), 'Estádio_974': (140,170), 'Estádio_Internacional_Khalifa': (170,240), 'Estádio_Lusail': (300,410), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (1150,1260), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (250,360), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (140,200), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (180,230)},  
        'Estádio_Al_Bayt':                                                      {'Estádio_Al_Thumama': (460, 600), 'Estádio_Al_Janoub': (550,670), 'Estádio_Al_Bayt': (0,0), 'Estádio_Ahmad_bin_Ali': (380,460), 'Estádio_Cidade_da_Educação': (380,460), 'Estádio_974': (400,520), 'Estádio_Internacional_Khalifa': (430,530), 'Estádio_Lusail': (250,310), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (610,750), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (3000,3600), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (420,490), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (390,4700)},
        'Estádio_Ahmad_bin_Ali':                                                {'Estádio_Al_Thumama': (210, 280), 'Estádio_Al_Janoub': (300,350), 'Estádio_Al_Bayt': (380,460), 'Estádio_Ahmad_bin_Ali': (0,0), 'Estádio_Cidade_da_Educação': (80,100), 'Estádio_974': (220,260), 'Estádio_Internacional_Khalifa': (120,150), 'Estádio_Lusail': (180,250), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (920,1030), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (160,200), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (180,210), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (140,160)},
        'Estádio_Cidade_da_Educação':                                           {'Estádio_Al_Thumama': (130, 210), 'Estádio_Al_Janoub': (220,280), 'Estádio_Al_Bayt': (380,470), 'Estádio_Ahmad_bin_Ali': (80,100), 'Estádio_Cidade_da_Educação': (0,0), 'Estádio_974': (140,180), 'Estádio_Internacional_Khalifa': (50,100), 'Estádio_Lusail': (140,210), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (950,1040), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (100,140), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (100,140), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (50,90)},
        'Estádio_974':                                                          {'Estádio_Al_Thumama': (60, 150), 'Estádio_Al_Janoub': (140,220), 'Estádio_Al_Bayt': (400,530), 'Estádio_Ahmad_bin_Ali': (220,310), 'Estádio_Cidade_da_Educação': (140,200), 'Estádio_974': (0,0), 'Estádio_Internacional_Khalifa': (120,170), 'Estádio_Lusail': (160,250), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (1010,1140), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (120,190), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (60,60), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (90,120)},
        'Estádio_Internacional_Khalifa':                                        {'Estádio_Al_Thumama': (90, 140), 'Estádio_Al_Janoub': (170,210), 'Estádio_Al_Bayt': (430,530), 'Estádio_Ahmad_bin_Ali': (120,200), 'Estádio_Cidade_da_Educação': (50,90), 'Estádio_974': (120,170), 'Estádio_Internacional_Khalifa': (0,0), 'Estádio_Lusail': (180,270), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (1010,1100), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (130,190), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (60,100), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (50,80)},   
        'Estádio_Lusail':                                                       {'Estádio_Al_Thumama': (210, 340), 'Estádio_Al_Janoub': (300,400), 'Estádio_Al_Bayt': (250,310), 'Estádio_Ahmad_bin_Ali': (180,250), 'Estádio_Cidade_da_Educação': (140,200), 'Estádio_974': (160,250), 'Estádio_Internacional_Khalifa': (180,260), 'Estádio_Lusail': (0,0), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (850,970), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (50,110), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (160,210), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (130,220)},           
        'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort':                          {'Estádio_Al_Thumama': (1060, 1180), 'Estádio_Al_Janoub': (1150,1250), 'Estádio_Al_Bayt': (610,760), 'Estádio_Ahmad_bin_Ali': (920,1040), 'Estádio_Cidade_da_Educação': (950,1040), 'Estádio_974': (1010,1160), 'Estádio_Internacional_Khalifa': (1010,1110), 'Estádio_Lusail': (850,980), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (0,0), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (900,1030), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (1010,1150), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (970,1060)},
        'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex':   {'Estádio_Al_Thumama': (160, 270), 'Estádio_Al_Janoub': (250,320), 'Estádio_Al_Bayt': (3000,3600), 'Estádio_Ahmad_bin_Ali': (160,220), 'Estádio_Cidade_da_Educação': (100,140), 'Estádio_974': (120,190), 'Estádio_Internacional_Khalifa': (13000,19000), 'Estádio_Lusail': (50,100), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (900,1020), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (0,0), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (110,150), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (80,120)},
        'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha':                         {'Estádio_Al_Thumama': (50, 110), 'Estádio_Al_Janoub': (140,180), 'Estádio_Al_Bayt': (420,500), 'Estádio_Ahmad_bin_Ali': (180,210), 'Estádio_Cidade_da_Educação': (90,150), 'Estádio_974': (60,80), 'Estádio_Internacional_Khalifa': (60,80), 'Estádio_Lusail': (160,220), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (1010,1100), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (110,160), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (0,0), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (40,70)},
        'Delegação_Francesa_(FFF)_Al_Messila_Resort':                           {'Estádio_Al_Thumama': (90, 160), 'Estádio_Al_Janoub': (180,230), 'Estádio_Al_Bayt': (390,470), 'Estádio_Ahmad_bin_Ali': (130,170), 'Estádio_Cidade_da_Educação': (50,80), 'Estádio_974': (90,130), 'Estádio_Internacional_Khalifa': (50,90), 'Estádio_Lusail': (130,210), 'Delegação_Alemã_(DFB)_Zulal_Wellness_Resort': (970,1040), 'Delegação_Argentina_(AFA)_Qatar_University_Sports_&_Events_Complex': (80,130), 'Delegação_Brasileira_(CBF)_Westin_Hotel_Doha': (40,80), 'Delegação_Francesa_(FFF)_Al_Messila_Resort': (0,0)},
    }
